# Generated by Django 4.2.1 on 2023-05-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_detalle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_xmayor_revendedores', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_xmayor_almacenes', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
